from ora.detection.killfeed import KillFeedEntry
from ora.player import KFPlayer
from ora.hero import populate_heroes

RED = 0
BLUE = 1

heroes = {x.name: x for x in populate_heroes()}
abilities = {ab.name: ab for x in heroes.values() for ab in x.abilities}


TC_ARROW_HARD = {
    'test_2520': [KillFeedEntry(frame=2520, row=1,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76']),
                                player2=KFPlayer(team=RED, hero=heroes['Hanzo']), ),
                  KillFeedEntry(frame=2280, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sigma'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                  ],

    'venom_5760': [KillFeedEntry(frame=5760, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                 is_critical=True,
                                 player2=KFPlayer(team=BLUE, hero=heroes['Mercy']), ),
                   KillFeedEntry(frame=5760, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                 ability=abilities['Quick melee'],
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   KillFeedEntry(frame=5760, row=2,
                                 player1=KFPlayer(team=RED, hero=heroes['Sojourn'], ),
                                 ability=abilities['Charged Shot'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Emre']), ),
                   ],
}


TC_SINGLE = {
    'ml7_1260': [KillFeedEntry(frame=1260, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Kiriko']),
                               player2=KFPlayer(team=RED, hero=heroes['Lúcio']), )],
    'ml7_1440': [KillFeedEntry(frame=1440, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Kiriko']),
                               player2=KFPlayer(team=RED, hero=heroes['Lúcio']), )],

    'ml7_2220': [KillFeedEntry(frame=2220, row=0,
                               player1=KFPlayer(team=RED, hero=heroes['Bastion']),
                               player2=KFPlayer(team=BLUE, hero=heroes['Pharah']), )],
    'ml7_2820': [KillFeedEntry(frame=2720, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper']),
                               player2=KFPlayer(team=RED, hero=heroes['Tracer']), )],

    'ml7_2940': [KillFeedEntry(frame=2940, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper']),
                               player2=KFPlayer(team=RED, hero=heroes['Tracer']), )],

    'ml7_3840': [KillFeedEntry(frame=3840, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                               player2=KFPlayer(team=RED, hero=heroes['Lúcio']), )],

    'ml7_3960': [KillFeedEntry(frame=3840, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                               player2=KFPlayer(team=RED, hero=heroes['Lúcio']), )],

    'ml7_4020': [KillFeedEntry(frame=4020, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                               player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                 KillFeedEntry(frame=4020, row=1,
                               player1=KFPlayer(team=RED, hero=heroes['Hazard']),
                               player2=KFPlayer(team=BLUE, hero=heroes['Ana']), )
                 ],

    'test_6480': [KillFeedEntry(frame=6480, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                                player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                  ],

    'test_6720': [KillFeedEntry(frame=6720, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                                player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),  # FIXME too many rows
                  ],

    'test_7380': [KillFeedEntry(frame=7380, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta']),
                                player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                  ],

    'test_7440': [KillFeedEntry(frame=7440, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta']),
                                player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                  ],

    'test_8400': [KillFeedEntry(frame=8400, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta']),
                                player2=KFPlayer(team=RED, hero=heroes['Mercy']), ),
                  ],

    'test_9780': [KillFeedEntry(frame=9780, row=0,
                                player1=KFPlayer(team=RED, hero=heroes['Sombra']),
                                player2=KFPlayer(team=BLUE, hero=heroes['Zenyatta']), ),
                  ],

    'test_15240': [KillFeedEntry(frame=15240, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76']),
                                 player2=KFPlayer(team=RED, hero=heroes['Mercy']), ),
                   ],

    'test_16140': [KillFeedEntry(frame=16140, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Sigma']),
                                 player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                   ],

    'test_17700': [KillFeedEntry(frame=17700, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76']),
                                 player2=KFPlayer(team=RED, hero=heroes['Cassidy']), ),
                   KillFeedEntry(frame=17700, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta']),
                                 player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),  # FIXME  incorrect heroes
                   ],

    'venom_18120': [KillFeedEntry(frame=18120, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                                  player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                    ],

    'venom_18180': [KillFeedEntry(frame=18180, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Ana']),
                                  player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                    ],
}

TC_ASSIST = {
    'test_2280': [KillFeedEntry(frame=2280, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sigma'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                  ],

    'test_2700': [KillFeedEntry(frame=2700, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sigma'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                  KillFeedEntry(frame=2700, row=1,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76']),
                                player2=KFPlayer(team=RED, hero=heroes['Hanzo']), ),
                  KillFeedEntry(frame=2700, row=2,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sojourn'], ),
                                         KFPlayer(team=BLUE, hero=heroes['Zenyatta'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                  ],

    'test_2820': [KillFeedEntry(frame=2820, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sojourn'], ),
                                         KFPlayer(team=BLUE, hero=heroes['Zenyatta'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                  ],

    'ml7_840': [KillFeedEntry(frame=840, row=0,
                              player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                              assists=[KFPlayer(team=BLUE, hero=heroes['Winston'], )],
                              player2=KFPlayer(team=RED, hero=heroes['Hazard']), ),
                ],

    'ml7_1020': [KillFeedEntry(frame=1020, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Winston'], )],
                               player2=KFPlayer(team=RED, hero=heroes['Hazard']), ),
                 ],

    'ml7_5460': [KillFeedEntry(frame=5460, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                        KFPlayer(team=BLUE, hero=heroes['Orisa'], )],
                               player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                 ],

    'ml7_8580': [KillFeedEntry(frame=8580, row=1,
                               player1=KFPlayer(team=BLUE, hero=heroes['Kiriko'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], )],
                               player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                 KillFeedEntry(frame=8580, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                                        KFPlayer(team=BLUE, hero=heroes['Kiriko'], )],
                               player2=KFPlayer(team=RED, hero=heroes['Reaper']), ),
                 ],

    'ml7_8700': [KillFeedEntry(frame=8700, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                                        KFPlayer(team=BLUE, hero=heroes['Kiriko'], )],
                               player2=KFPlayer(team=RED, hero=heroes['Reaper']), ),
                 KillFeedEntry(frame=8700, row=1,
                               player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Winston'], ),
                                        KFPlayer(team=BLUE, hero=heroes['Kiriko'], )],
                               player2=KFPlayer(team=RED, hero=heroes['Cassidy']), ),
                 ],

    'venom_2580': [KillFeedEntry(frame=2580, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Ana'], )],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                   ],

    'venom_2640': [KillFeedEntry(frame=2640, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Ana'], )],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                   ],

    'venom_12660': [KillFeedEntry(frame=12660, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], ),
                                           KFPlayer(team=BLUE, hero=heroes['Ana'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Mauga']), ),
                    ],

    'venom_12840': [KillFeedEntry(frame=12840, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], ),
                                           KFPlayer(team=BLUE, hero=heroes['Ana'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Mauga']), ),
                    ],

    'venom_14580': [KillFeedEntry(frame=14580, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Sojourn'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Sojourn']), ),
                    ],

    'venom_16860': [KillFeedEntry(frame=16860, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], ),
                                           KFPlayer(team=BLUE, hero=heroes['Ana'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                    ],

    'venom_16980': [KillFeedEntry(frame=16980, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),  # FIXME incorrect assists
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], ),
                                           KFPlayer(team=BLUE, hero=heroes['Ana'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                    KillFeedEntry(frame=16980, row=1,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Mercy']), ),
                    KillFeedEntry(frame=16980, row=2,
                                  player1=KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                  assists=[KFPlayer(team=RED, hero=heroes['Mercy'], )],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Emre']), ),
                    ],

}

TC_CRITICAL = {
    'test_3240': [KillFeedEntry(frame=3240, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                is_critical=True,
                                player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                  ],
    'test_3300': [KillFeedEntry(frame=3300, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                is_critical=True,
                                player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                  ],
    'test_3360': [KillFeedEntry(frame=3360, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                is_critical=True,
                                player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                  ],

    'test_3900': [KillFeedEntry(frame=3900, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Sojourn'], ),
                                is_critical=True,
                                player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                  ],

    'test_4140': [KillFeedEntry(frame=4140, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Sojourn'], ),
                                is_critical=True,
                                player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                  ],

    'test_5040': [KillFeedEntry(frame=5040, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76'], ),
                                is_critical=True,
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sigma'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                  ],

    'test_5100': [KillFeedEntry(frame=5100, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76'], ),
                                is_critical=True,
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sigma'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                  ],

    'test_20280': [KillFeedEntry(frame=20280, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Hanzo'], ),
                                 is_critical=True,
                                 player2=KFPlayer(team=RED, hero=heroes['Soldier_76']), ),
                   ],

    'venom_3960': [KillFeedEntry(frame=3960, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                 is_critical=True,
                                 assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], )],
                                 player2=KFPlayer(team=RED, hero=heroes['Sojourn']), ),
                   ],

    'venom_4020': [KillFeedEntry(frame=4020, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                 is_critical=True,
                                 assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], )],
                                 player2=KFPlayer(team=RED, hero=heroes['Sojourn']), ),
                   ],

    'venom_13380': [KillFeedEntry(frame=13380, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], )],
                                  player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                    KillFeedEntry(frame=13380, row=1,
                                  player1=KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                  is_critical=True,
                                  player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                    ],

    'venom_17940': [KillFeedEntry(frame=17940, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                           KFPlayer(team=BLUE, hero=heroes['Mercy'], )],
                                  is_critical=True,
                                  player2=KFPlayer(team=RED, hero=heroes['Mauga']), ),
                    KillFeedEntry(frame=17940, row=1,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                  player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                    ],

    'ml7_600': [KillFeedEntry(frame=600, row=0,
                              player1=KFPlayer(team=RED, hero=heroes['Bastion'], ),
                              is_critical=True,
                              player2=KFPlayer(team=BLUE, hero=heroes['Pharah']), ),
                ],

    'ml7_660': [KillFeedEntry(frame=660, row=0,
                              player1=KFPlayer(team=RED, hero=heroes['Bastion'], ),
                              is_critical=True,
                              player2=KFPlayer(team=BLUE, hero=heroes['Pharah']), ),
                ],

    'ml7_9300': [KillFeedEntry(frame=9300, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               is_critical=True,
                               player2=KFPlayer(team=RED, hero=heroes['Kiriko']), ),
                 ],

    'ml7_9360': [KillFeedEntry(frame=9360, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               is_critical=True,
                               player2=KFPlayer(team=RED, hero=heroes['Kiriko']), ),
                 ],

    'ml7_12600': [KillFeedEntry(frame=12600, row=0,
                                player1=KFPlayer(team=RED, hero=heroes['Kiriko'], ),
                                is_critical=True,
                                player2=KFPlayer(team=BLUE, hero=heroes['Kiriko']), ),
                  ],

}

TC_ENVIRONMENTAL = {
    'ml7_7080': [KillFeedEntry(frame=7080, row=0,
                               player1=KFPlayer(team=RED, hero=heroes['Lúcio'], ),
                               ability=abilities['Soundwave'],
                               is_environmental=True,
                               player2=KFPlayer(team=BLUE, hero=heroes['Winston']), ),
                 ],
    'astro_17760': [KillFeedEntry(frame=17760, row=0,
                                  player1=KFPlayer(team=RED, hero=heroes['Emre']),
                                  player2=KFPlayer(team=BLUE, hero=heroes['Jetpack Cat']), ),
                    KillFeedEntry(frame=17760, row=1,
                                  player1=None,
                                  is_environmental=True,
                                  player2=KFPlayer(team=BLUE, hero=heroes['Domina']), ),

                    ],
}

TC_ABILITIES = {
    'test_5460': [KillFeedEntry(frame=5460, row=0,  # FIXME
                                player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Zenyatta'], )],
                                ability=abilities['Quick melee'],
                                player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                  ],
    'test_8100': [KillFeedEntry(frame=8100, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Sojourn'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Ana']), ),

                  KillFeedEntry(frame=8100, row=1,
                                player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Zenyatta'], )],
                                ability=abilities['Quick melee'],
                                player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                  ],

    'test_11640': [KillFeedEntry(frame=11640, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Genji'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Ana'], ),
                                          KFPlayer(team=RED, hero=heroes['Sombra'], )],
                                 ability=abilities['Dragonblade'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                   ],

    'test_12420': [KillFeedEntry(frame=12420, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   KillFeedEntry(frame=12420, row=1,
                                 player1=None,
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sigma']), ),
                   KillFeedEntry(frame=12420, row=2,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Sigma'], ),
                                 ability=abilities['Accretion'],
                                 player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                   ],

    'test_12600': [KillFeedEntry(frame=12600, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   KillFeedEntry(frame=12420, row=1,
                                 player1=None,
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sigma']), ),
                   KillFeedEntry(frame=12420, row=2,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Sigma'], ),
                                 ability=abilities['Accretion'],
                                 player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                   KillFeedEntry(frame=12600, row=3,
                                 player1=KFPlayer(team=RED, hero=heroes['Orisa'], ),
                                 ability=abilities['Energy Javelin'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Zenyatta']), ),
                   ],

    'test_14880': [KillFeedEntry(frame=14880, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Sojourn'], ),
                                 ability=abilities['Overclock'],
                                 player2=KFPlayer(team=RED, hero=heroes['Soldier_76']), ),
                   ],

    'test_17880': [KillFeedEntry(frame=17880, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Zenyatta'], ),
                                 player2=KFPlayer(team=RED, hero=heroes['Sombra']), ),
                   KillFeedEntry(frame=17880, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Soldier_76'], ),
                                 ability=abilities['Helix Rockets'],
                                 player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                   ],

    'test_19080': [KillFeedEntry(frame=19080, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Hanzo'], ),
                                 ability=abilities['Storm Arrows'],
                                 is_critical=True,
                                 player2=KFPlayer(team=RED, hero=heroes['Zenyatta']), ),
                   ],

    'ml7_420': [KillFeedEntry(frame=420, row=0,
                              player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                              player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                KillFeedEntry(frame=420, row=1,
                              player1=KFPlayer(team=RED, hero=heroes['Hazard'], ),
                              ability=abilities['Violent Leap'],
                              player2=KFPlayer(team=BLUE, hero=heroes['Kiriko']), ),
                ],

    'ml7_480': [KillFeedEntry(frame=480, row=0,
                              player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                              player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                KillFeedEntry(frame=480, row=1,
                              player1=KFPlayer(team=RED, hero=heroes['Hazard'], ),
                              ability=abilities['Violent Leap'],
                              player2=KFPlayer(team=BLUE, hero=heroes['Kiriko']), ),
                KillFeedEntry(frame=480, row=2,
                              player1=KFPlayer(team=RED, hero=heroes['Tracer'], ),
                              player2=KFPlayer(team=BLUE, hero=heroes['Ana']), ),
                ],

    'ml7_1620': [KillFeedEntry(frame=1620, row=0,
                               player1=KFPlayer(team=RED, hero=heroes['Tracer'], ),
                               ability=abilities['Pulse Bomb'],
                               player2=KFPlayer(team=BLUE, hero=heroes['Ana']), ),
                 ],

    'ml7_2400': [KillFeedEntry(frame=2400, row=0,
                               player1=KFPlayer(team=RED, hero=heroes['Bastion'], ),
                               player2=KFPlayer(team=BLUE, hero=heroes['Pharah']), ),
                 KillFeedEntry(frame=2400, row=1,
                               player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Pharah'], )],
                               ability=abilities['Biotic Grenade'],
                               player2=KFPlayer(team=RED, hero=heroes['Bastion']), ),
                 ],

    'ml7_4200': [KillFeedEntry(frame=4200, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Kiriko'], ),
                               player2=KFPlayer(team=RED, hero=heroes['Hazard']), ),
                 KillFeedEntry(frame=4200, row=1,
                               player1=KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                               player2=KFPlayer(team=RED, hero=heroes['Bastion']), ),
                 KillFeedEntry(frame=4200, row=2,
                               player1=KFPlayer(team=BLUE, hero=heroes['Winston'], ),
                               ability=abilities['Quick melee'],
                               player2=KFPlayer(team=RED, hero=heroes['Kiriko']), ),
                 ],

    'ml7_5220': [KillFeedEntry(frame=5220, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                                        KFPlayer(team=BLUE, hero=heroes['Ana'], ), ],
                               ability=abilities['Death Blossom'],
                               player2=KFPlayer(team=RED, hero=heroes['Kiriko']), ),
                 KillFeedEntry(frame=5220, row=1,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ), ],
                               ability=abilities['Death Blossom'],
                               player2=KFPlayer(team=RED, hero=heroes['Bastion']), ),
                 KillFeedEntry(frame=5220, row=2,
                               player1=KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ), ],
                               player2=KFPlayer(team=RED, hero=heroes['Cassidy']), ),
                 KillFeedEntry(frame=5220, row=3,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ), ],
                               ability=abilities['Death Blossom'],
                               player2=KFPlayer(team=RED, hero=heroes['Lúcio']), ),
                 KillFeedEntry(frame=5220, row=4,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                        KFPlayer(team=BLUE, hero=heroes['Orisa'], ), ],
                               player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                 ],

    'ml7_9600': [KillFeedEntry(frame=9600, row=0,
                               player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                               is_critical=True,
                               player2=KFPlayer(team=RED, hero=heroes['Kiriko']), ),
                 KillFeedEntry(frame=9600, row=1,
                               player1=KFPlayer(team=BLUE, hero=heroes['Winston'], ),
                               ability=abilities['Quick melee'],
                               player2=KFPlayer(team=RED, hero=heroes['Cassidy']), ),
                 ],

    'ml7_11460': [KillFeedEntry(frame=11460, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Winston'], )],
                                player2=KFPlayer(team=RED, hero=heroes['Kiriko']), ),
                  KillFeedEntry(frame=11460, row=1,
                                player1=KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                                ability=abilities['Barrage'],
                                player2=KFPlayer(team=RED, hero=heroes['Reaper']), ),
                  KillFeedEntry(frame=11460, row=2,
                                player1=KFPlayer(team=BLUE, hero=heroes['Pharah'], ),
                                ability=abilities['Barrage'],
                                player2=KFPlayer(team=RED, hero=heroes['Orisa']), ),
                  ],

    'ml7_12300': [KillFeedEntry(frame=12300, row=0,
                                player1=KFPlayer(team=BLUE, hero=heroes['Reaper'], ),
                                assists=[KFPlayer(team=BLUE, hero=heroes['Pharah'], ),],
                                ability=abilities['Death Blossom'],
                                player2=KFPlayer(team=RED, hero=heroes['Tracer']), ),
                  ],

    'venom_0': [KillFeedEntry(frame=0, row=0,
                              player1=KFPlayer(team=RED, hero=heroes['Ana'], ),
                              assists=[KFPlayer(team=RED, hero=heroes['Mercy'], ), ],
                              ability=abilities['Biotic Grenade'],
                              player2=KFPlayer(team=BLUE, hero=heroes['Emre']), ),
                ],

    'venom_2220': [KillFeedEntry(frame=2220, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                 assists=[KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                          KFPlayer(team=BLUE, hero=heroes['Mercy'], ), ],
                                 ability=abilities['Siphon Blaster'],
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   ],

    'venom_3060': [KillFeedEntry(frame=3060, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Mercy'], ),
                                 ability=abilities['Resurrect'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                   ],

    'venom_5100': [KillFeedEntry(frame=5100, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                 assists=[KFPlayer(team=BLUE, hero=heroes['Mercy'], ), ],
                                 player2=KFPlayer(team=RED, hero=heroes['Ana']), ),
                   KillFeedEntry(frame=5100, row=1,
                                 player1=KFPlayer(team=RED, hero=heroes['Genji'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Mercy'], ),
                                          KFPlayer(team=RED, hero=heroes['Ana'], ), ],
                                 ability=abilities['Swift Strike'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                   ],

    'venom_5280': [KillFeedEntry(frame=5280, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Genji'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Mercy'], ),
                                          KFPlayer(team=RED, hero=heroes['Ana'], ), ],
                                 ability=abilities['Swift Strike'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Sojourn']), ),
                   KillFeedEntry(frame=5280, row=1,
                                 player1=KFPlayer(team=RED, hero=heroes['Sojourn'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Mercy'], ),
                                          KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                          KFPlayer(team=RED, hero=heroes['Ana'], ), ],
                                 ability=abilities['Disruptor Shot'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Domina']), ),
                   KillFeedEntry(frame=5280, row=2,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                 ability=abilities['Panopticon'],
                                 player2=KFPlayer(team=RED, hero=heroes['Mercy']), ),
                   ],

    'venom_5820': [KillFeedEntry(frame=5820, row=0,   # fixme charged shot undetected
                                 player1=KFPlayer(team=RED, hero=heroes['Mauga'], ),
                                 is_critical=True,
                                 player2=KFPlayer(team=BLUE, hero=heroes['Mercy']), ),
                   KillFeedEntry(frame=5820, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                 ability=abilities['Quick melee'],
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   KillFeedEntry(frame=5820, row=2,
                                 player1=KFPlayer(team=RED, hero=heroes['Sojourn'], ),
                                 ability=abilities['Charged Shot'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Emre']), ),
                   ],

    'venom_6000': [KillFeedEntry(frame=6000, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Ana'], ),
                                 ability=abilities['Quick melee'],
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   KillFeedEntry(frame=6000, row=1,
                                 player1=KFPlayer(team=RED, hero=heroes['Sojourn'], ),
                                 ability=abilities['Charged Shot'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Emre']), ),
                   KillFeedEntry(frame=6000, row=2,
                                 player1=KFPlayer(team=RED, hero=heroes['Sojourn'], ),
                                 assists=[KFPlayer(team=RED, hero=heroes['Mauga'], ),],
                                 ability=abilities['Charged Shot'],
                                 player2=KFPlayer(team=BLUE, hero=heroes['Ana']), ),
                   ],

    'venom_8400': [KillFeedEntry(frame=8400, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Mercy'], ),
                                 ability=abilities['Resurrect'],
                                 player2=KFPlayer(team=RED, hero=heroes['Genji']), ),
                   ],

    'astro_3840': [KillFeedEntry(frame=3840, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                 ability=abilities['Crystal Charge'],
                                 player2=KFPlayer(team=RED, hero=heroes['Domina']), ),
                   ],

    'astro_4140': [KillFeedEntry(frame=4140, row=0,  # FIXME assists
                                 player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                 ability=abilities['Crystal Charge'],
                                 player2=KFPlayer(team=RED, hero=heroes['Domina']), ),
                   KillFeedEntry(frame=4140, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Anran'], ),
                                 ability=abilities['Fan the Flames'],
                                 is_critical=True,
                                 player2=KFPlayer(team=RED, hero=heroes['Mizuki']), ),
                   ],

    'astro_4680': [KillFeedEntry(frame=4680, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Anran'], ),
                                 ability=abilities['Ignition'],
                                 player2=KFPlayer(team=RED, hero=heroes['Anran']), ),
                   ],

    'astro_4920': [KillFeedEntry(frame=4920, row=0,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Anran'], ),
                                 ability=abilities['Ignition'],
                                 player2=KFPlayer(team=RED, hero=heroes['Anran']), ),
                   KillFeedEntry(frame=4920, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Jetpack Cat'], ),
                                 is_critical=True,
                                 player2=KFPlayer(team=RED, hero=heroes['Emre']), ),
                   ],

    'astro_7500': [KillFeedEntry(frame=7500, row=0,   # FIXME fan the flames undetected
                                 player1=KFPlayer(team=RED, hero=heroes['Anran'], ),
                                 is_critical=True,
                                 player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                   KillFeedEntry(frame=7500, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Anran'], ),
                                 ability=abilities['Fan the Flames'],
                                 is_critical=True,
                                 player2=KFPlayer(team=RED, hero=heroes['Anran']), ),
                   ],

    'astro_7620': [KillFeedEntry(frame=7620, row=0,
                                 player1=KFPlayer(team=RED, hero=heroes['Anran'], ),
                                 is_critical=True,
                                 player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                   KillFeedEntry(frame=7620, row=1,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Anran'], ),
                                 ability=abilities['Fan the Flames'],
                                 is_critical=True,
                                 player2=KFPlayer(team=RED, hero=heroes['Anran']), ),
                   KillFeedEntry(frame=7620, row=2,
                                 player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                 ability=abilities['Cyber Frag'],
                                 player2=KFPlayer(team=RED, hero=heroes['Mizuki']), ),
                   ],

    'astro_10080': [KillFeedEntry(frame=10080, row=0,  # FIXME
                                  player1=KFPlayer(team=RED, hero=heroes['Emre'], ),
                                  player2=KFPlayer(team=BLUE, hero=heroes['Emre']), ),
                    KillFeedEntry(frame=10080, row=1,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mizuki'], ),],
                                  player2=KFPlayer(team=RED, hero=heroes['Domina']), ),
                    KillFeedEntry(frame=10080, row=2,
                                  player1=KFPlayer(team=RED, hero=heroes['Jetpack Cat'], ),
                                  ability=abilities['Purr'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                    ],

    'astro_10140': [KillFeedEntry(frame=10140, row=0,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Domina'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Mizuki'], ), ],
                                  player2=KFPlayer(team=RED, hero=heroes['Domina']), ),
                    KillFeedEntry(frame=10140, row=0,
                                  player1=KFPlayer(team=RED, hero=heroes['Jetpack Cat'], ),
                                  ability=abilities['Purr'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                    ],

    'astro_12360': [KillFeedEntry(frame=12360, row=0,
                                  player1=KFPlayer(team=RED, hero=heroes['Anran'], ),
                                  ability=abilities['Dancing Blaze'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                    ],

    'astro_12480': [KillFeedEntry(frame=12480, row=0,
                                  player1=KFPlayer(team=RED, hero=heroes['Anran'], ),
                                  ability=abilities['Dancing Blaze'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                    KillFeedEntry(frame=12480, row=1,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Anran'], ),
                                  ability=abilities['Vermillion Revival'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),
                    ],

    'astro_12960': [KillFeedEntry(frame=12960, row=0,   # FIXME catnapper undetected
                                  player1=KFPlayer(team=RED, hero=heroes['Jetpack Cat'], ),
                                  ability=abilities['Quick melee'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Mizuki']), ),
                    KillFeedEntry(frame=12960, row=1,
                                  player1=KFPlayer(team=BLUE, hero=heroes['Jetpack Cat'], ),
                                  ability=abilities['Catnapper'],
                                  is_environmental=True,
                                  player2=KFPlayer(team=RED, hero=heroes['Domina']), ),
                    KillFeedEntry(frame=12960, row=2,
                                  player1=KFPlayer(team=RED, hero=heroes['Emre'], ),
                                  ability=abilities['Override Protocol'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Anran']), ),

                    ],

    'astro_13740': [KillFeedEntry(frame=13740, row=0,   # FIXME mizuki assist
                                  player1=KFPlayer(team=BLUE, hero=heroes['Emre'], ),
                                  assists=[KFPlayer(team=BLUE, hero=heroes['Domina'], ), ],
                                  player2=KFPlayer(team=RED, hero=heroes['Jetpack Cat']), ),
                    KillFeedEntry(frame=13740, row=1,
                                  player1=KFPlayer(team=RED, hero=heroes['Anran'], ),
                                  assists=[KFPlayer(team=RED, hero=heroes['Mizuki'], ), ],
                                  ability=abilities['Inferno Rush'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Domina']), ),

                    ],
    #
    'astro_16380': [KillFeedEntry(frame=16380, row=0,  # FIXME mizuki assist
                                  player1=KFPlayer(team=RED, hero=heroes['Anran'], ),
                                  assists=[KFPlayer(team=RED, hero=heroes['Mizuki'], ), ],
                                  ability=abilities['Vermillion Ascent'],
                                  player2=KFPlayer(team=BLUE, hero=heroes['Domina']), ),

                    ],

}
